### ISSUE TITLE
Code of Conduct Header does not resize on mobile

### ISSUE THREAD

**Issue by spyhi** [jsconfhi/jsconfhi#12]
iPhone screenshot:

![AB4AB832-6082-4D45-B678-7AA86B6DDF09](https://user-images.githubusercontent.com/8252806/62497983-5d8da300-b779-11e9-8218-e99ff58e6407.jpeg)

**Comment by jkup** [comment]
<img width="511" alt="Screen Shot 2019-09-21 at 9 49 18 PM" src="https://user-images.githubusercontent.com/490294/65382430-d5784400-dcb9-11e9-8612-6593cce0ca43.png">
